version: '3.4'

services:
  db:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=2000'

volumes:
  pgdata: